const a = {
  businessDate: '2023-05-24',
  subMatchList: [
    {
      awayRank: '[瑞超3]',
      awayTeamAbbEnName: 'HAC',
      awayTeamAbbName: '赫根',
      awayTeamAllName: '赫根',
      awayTeamCode: 'HAC',
      awayTeamId: 604,
      backColor: '004488',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '2.27',
        af: '0',
        d: '3.45',
        df: '0',
        goalLine: '',
        h: '2.45',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '12:16:57',
      },
      hafu: {},
      hhad: {
        a: '4.75',
        af: '0',
        d: '4.10',
        df: '0',
        goalLine: '+1',
        h: '1.46',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '12:17:19',
      },
      homeRank: '[瑞超7]',
      homeTeamAbbEnName: 'DJU',
      homeTeamAbbName: '佐加顿斯',
      homeTeamAllName: '佐加顿斯',
      homeTeamCode: 'DJU',
      homeTeamId: 294,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '瑞超',
      leagueAllName: '瑞典超级联赛',
      leagueCode: 'SAL',
      leagueId: 58,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019597,
      matchName: '',
      matchNum: 3001,
      matchNumStr: '周三001',
      matchStatus: 'Selling',
      matchTime: '01:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090797,
          updateDate: '2023-05-23',
          updateTime: '13:31:30',
        },
        {
          a: '2.270',
          d: '3.450',
          goalLine: '',
          goalLineF: '',
          h: '2.450',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090797,
          updateDate: '2023-05-24',
          updateTime: '12:16:57',
        },
        {
          a: '4.750',
          d: '4.100',
          goalLine: '+1',
          goalLineF: '',
          h: '1.460',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090797,
          updateDate: '2023-05-24',
          updateTime: '12:17:19',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090800,
          updateDate: '2023-05-23',
          updateTime: '13:31:30',
        },
        {
          a: '2.270',
          d: '3.450',
          goalLine: '',
          goalLineF: '',
          h: '2.450',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090800,
          updateDate: '2023-05-24',
          updateTime: '12:16:57',
        },
        {
          a: '4.750',
          d: '4.100',
          goalLine: '+1',
          goalLineF: '',
          h: '1.460',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090800,
          updateDate: '2023-05-24',
          updateTime: '12:17:19',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090803,
          updateDate: '2023-05-23',
          updateTime: '13:31:30',
        },
        {
          a: '2.270',
          d: '3.450',
          goalLine: '',
          goalLineF: '',
          h: '2.450',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090803,
          updateDate: '2023-05-24',
          updateTime: '12:16:57',
        },
        {
          a: '4.750',
          d: '4.100',
          goalLine: '+1',
          goalLineF: '',
          h: '1.460',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090803,
          updateDate: '2023-05-24',
          updateTime: '12:17:19',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090797,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090800,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090803,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '17.00',
        s0f: '0',
        s1: '6.50',
        s1f: '0',
        s2: '3.85',
        s2f: '0',
        s3: '3.65',
        s3f: '0',
        s4: '4.90',
        s4f: '0',
        s5: '7.75',
        s5f: '0',
        s6: '14.00',
        s6f: '0',
        s7: '19.00',
        s7f: '0',
        updateDate: '2023-05-23',
        updateTime: '13:31:30',
      },
      vote: {},
    },
    {
      awayRank: '[西甲11]',
      awayTeamAbbEnName: 'VNO',
      awayTeamAbbName: '巴列卡诺',
      awayTeamAllName: '巴列卡诺',
      awayTeamCode: 'VNO',
      awayTeamId: 849,
      backColor: '006633',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '6.10',
        af: '1',
        d: '4.60',
        df: '1',
        goalLine: '',
        h: '1.32',
        hf: '-1',
        updateDate: '2023-05-24',
        updateTime: '14:43:04',
      },
      hafu: {},
      hhad: {
        a: '2.65',
        af: '1',
        d: '3.65',
        df: '1',
        goalLine: '-1',
        h: '2.05',
        hf: '-1',
        updateDate: '2023-05-24',
        updateTime: '14:43:22',
      },
      homeRank: '[西甲3]',
      homeTeamAbbEnName: 'RMD',
      homeTeamAbbName: '皇马',
      homeTeamAllName: '皇家马德里',
      homeTeamCode: 'RMD',
      homeTeamId: 664,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '西甲',
      leagueAllName: '西班牙甲级联赛',
      leagueCode: 'SFL',
      leagueId: 62,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019598,
      matchName: '',
      matchNum: 3002,
      matchNumStr: '周三002',
      matchStatus: 'Selling',
      matchTime: '01:30:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '2.650',
          d: '3.650',
          goalLine: '-1',
          goalLineF: '',
          h: '2.050',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090770,
          updateDate: '2023-05-24',
          updateTime: '14:43:22',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090770,
          updateDate: '2023-05-23',
          updateTime: '09:30:46',
        },
        {
          a: '6.100',
          d: '4.600',
          goalLine: '',
          goalLineF: '',
          h: '1.320',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090770,
          updateDate: '2023-05-24',
          updateTime: '14:43:04',
        },
        {
          a: '2.650',
          d: '3.650',
          goalLine: '-1',
          goalLineF: '',
          h: '2.050',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090745,
          updateDate: '2023-05-24',
          updateTime: '14:43:22',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090745,
          updateDate: '2023-05-23',
          updateTime: '09:30:46',
        },
        {
          a: '6.100',
          d: '4.600',
          goalLine: '',
          goalLineF: '',
          h: '1.320',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090745,
          updateDate: '2023-05-24',
          updateTime: '14:43:04',
        },
        {
          a: '2.650',
          d: '3.650',
          goalLine: '-1',
          goalLineF: '',
          h: '2.050',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090743,
          updateDate: '2023-05-24',
          updateTime: '14:43:22',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090743,
          updateDate: '2023-05-23',
          updateTime: '09:30:46',
        },
        {
          a: '6.100',
          d: '4.600',
          goalLine: '',
          goalLineF: '',
          h: '1.320',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090743,
          updateDate: '2023-05-24',
          updateTime: '14:43:04',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090770,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090745,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090743,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '18.00',
        s0f: '0',
        s1: '6.10',
        s1f: '0',
        s2: '3.90',
        s2f: '0',
        s3: '3.75',
        s3f: '0',
        s4: '4.80',
        s4f: '0',
        s5: '7.75',
        s5f: '0',
        s6: '14.00',
        s6f: '0',
        s7: '19.00',
        s7f: '0',
        updateDate: '2023-05-23',
        updateTime: '09:30:46',
      },
      vote: {},
    },
    {
      awayRank: '[Group D2]',
      awayTeamAbbEnName: 'NG2',
      awayTeamAbbName: '尼日利20',
      awayTeamAllName: '尼日利亚U20',
      awayTeamCode: 'NG2',
      awayTeamId: 662,
      backColor: '3A5500',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '4.50',
        af: '0',
        d: '3.40',
        df: '0',
        goalLine: '',
        h: '1.61',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:10',
      },
      hafu: {},
      hhad: {
        a: '1.97',
        af: '0',
        d: '3.35',
        df: '0',
        goalLine: '-1',
        h: '3.00',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:08',
      },
      homeRank: '[Group D1]',
      homeTeamAbbEnName: 'IT2',
      homeTeamAbbName: '意大利20',
      homeTeamAllName: '意大利U20',
      homeTeamCode: 'IT2',
      homeTeamId: 657,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '世青赛',
      leagueAllName: '世界U20锦标赛',
      leagueCode: 'WYC',
      leagueId: 75,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019599,
      matchName: '',
      matchNum: 3003,
      matchNumStr: '周三003',
      matchStatus: 'Selling',
      matchTime: '02:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090818,
          updateDate: '2023-05-24',
          updateTime: '12:36:11',
        },
        {
          a: '4.500',
          d: '3.400',
          goalLine: '',
          goalLineF: '',
          h: '1.610',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090818,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.970',
          d: '3.350',
          goalLine: '-1',
          goalLineF: '',
          h: '3.000',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090818,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090820,
          updateDate: '2023-05-24',
          updateTime: '12:36:11',
        },
        {
          a: '4.500',
          d: '3.400',
          goalLine: '',
          goalLineF: '',
          h: '1.610',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090820,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.970',
          d: '3.350',
          goalLine: '-1',
          goalLineF: '',
          h: '3.000',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090820,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090816,
          updateDate: '2023-05-24',
          updateTime: '12:36:11',
        },
        {
          a: '4.500',
          d: '3.400',
          goalLine: '',
          goalLineF: '',
          h: '1.610',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090816,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.970',
          d: '3.350',
          goalLine: '-1',
          goalLineF: '',
          h: '3.000',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090816,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090818,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090820,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090816,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '该场比赛将在阿根廷-门多萨举行。',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '11.00',
        s0f: '0',
        s1: '4.50',
        s1f: '-1',
        s2: '3.40',
        s2f: '-1',
        s3: '3.60',
        s3f: '0',
        s4: '6.00',
        s4f: '1',
        s5: '12.00',
        s5f: '1',
        s6: '23.00',
        s6f: '1',
        s7: '38.00',
        s7f: '1',
        updateDate: '2023-05-24',
        updateTime: '12:36:11',
      },
      vote: {},
    },
    {
      awayRank: '[英超1]',
      awayTeamAbbEnName: 'MNC',
      awayTeamAbbName: '曼城',
      awayTeamAllName: '曼彻斯特城',
      awayTeamCode: 'MNC',
      awayTeamId: 12,
      backColor: 'FF3333',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '1.76',
        af: '1',
        d: '3.70',
        df: '-1',
        goalLine: '',
        h: '3.32',
        hf: '-1',
        updateDate: '2023-05-24',
        updateTime: '14:59:44',
      },
      hafu: {},
      hhad: {
        a: '3.22',
        af: '1',
        d: '3.75',
        df: '1',
        goalLine: '+1',
        h: '1.78',
        hf: '-1',
        updateDate: '2023-05-24',
        updateTime: '15:00:00',
      },
      homeRank: '[英超6]',
      homeTeamAbbEnName: 'BRI',
      homeTeamAbbName: '布赖顿',
      homeTeamAllName: '布赖顿',
      homeTeamCode: 'BRI',
      homeTeamId: 41,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '英超',
      leagueAllName: '英格兰超级联赛',
      leagueCode: 'EPL',
      leagueId: 25,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019600,
      matchName: '',
      matchNum: 3004,
      matchNumStr: '周三004',
      matchStatus: 'Selling',
      matchTime: '03:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '3.220',
          d: '3.750',
          goalLine: '+1',
          goalLineF: '',
          h: '1.780',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090761,
          updateDate: '2023-05-24',
          updateTime: '15:00:00',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090761,
          updateDate: '2023-05-24',
          updateTime: '15:07:38',
        },
        {
          a: '1.760',
          d: '3.700',
          goalLine: '',
          goalLineF: '',
          h: '3.320',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090761,
          updateDate: '2023-05-24',
          updateTime: '14:59:44',
        },
        {
          a: '3.220',
          d: '3.750',
          goalLine: '+1',
          goalLineF: '',
          h: '1.780',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090756,
          updateDate: '2023-05-24',
          updateTime: '15:00:00',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090756,
          updateDate: '2023-05-24',
          updateTime: '15:07:38',
        },
        {
          a: '1.760',
          d: '3.700',
          goalLine: '',
          goalLineF: '',
          h: '3.320',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090756,
          updateDate: '2023-05-24',
          updateTime: '14:59:44',
        },
        {
          a: '3.220',
          d: '3.750',
          goalLine: '+1',
          goalLineF: '',
          h: '1.780',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090760,
          updateDate: '2023-05-24',
          updateTime: '15:00:00',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090760,
          updateDate: '2023-05-24',
          updateTime: '15:07:38',
        },
        {
          a: '1.760',
          d: '3.700',
          goalLine: '',
          goalLineF: '',
          h: '3.320',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090760,
          updateDate: '2023-05-24',
          updateTime: '14:59:44',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090761,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090756,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090760,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '21.00',
        s0f: '0',
        s1: '7.00',
        s1f: '-1',
        s2: '4.25',
        s2f: '-1',
        s3: '3.65',
        s3f: '0',
        s4: '4.50',
        s4f: '0',
        s5: '7.00',
        s5f: '1',
        s6: '13.00',
        s6f: '1',
        s7: '16.00',
        s7f: '0',
        updateDate: '2023-05-24',
        updateTime: '15:07:38',
      },
      vote: {},
    },
    {
      awayRank: '',
      awayTeamAbbEnName: 'INM',
      awayTeamAbbName: '国际米兰',
      awayTeamAllName: '国际米兰',
      awayTeamCode: 'INM',
      awayTeamId: 123,
      backColor: '3C3CFF',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '1.73',
        af: '1',
        d: '3.25',
        df: '-1',
        goalLine: '',
        h: '3.95',
        hf: '-1',
        updateDate: '2023-05-24',
        updateTime: '14:50:49',
      },
      hafu: {},
      hhad: {
        a: '3.32',
        af: '-1',
        d: '3.40',
        df: '-1',
        goalLine: '+1',
        h: '1.84',
        hf: '1',
        updateDate: '2023-05-24',
        updateTime: '14:38:29',
      },
      homeRank: '',
      homeTeamAbbEnName: 'FIO',
      homeTeamAbbName: '佛罗伦萨',
      homeTeamAllName: '佛罗伦萨',
      homeTeamCode: 'FIO',
      homeTeamId: 122,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '意大利杯',
      leagueAllName: '意大利杯',
      leagueCode: 'IFC',
      leagueId: 38,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019601,
      matchName: '',
      matchNum: 3005,
      matchNumStr: '周三005',
      matchStatus: 'Selling',
      matchTime: '03:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '3.320',
          d: '3.400',
          goalLine: '+1',
          goalLineF: '',
          h: '1.840',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090772,
          updateDate: '2023-05-24',
          updateTime: '14:38:29',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090772,
          updateDate: '2023-05-24',
          updateTime: '12:58:57',
        },
        {
          a: '1.730',
          d: '3.250',
          goalLine: '',
          goalLineF: '',
          h: '3.950',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090772,
          updateDate: '2023-05-24',
          updateTime: '14:50:49',
        },
        {
          a: '3.320',
          d: '3.400',
          goalLine: '+1',
          goalLineF: '',
          h: '1.840',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090769,
          updateDate: '2023-05-24',
          updateTime: '14:38:29',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090769,
          updateDate: '2023-05-24',
          updateTime: '12:58:57',
        },
        {
          a: '1.730',
          d: '3.250',
          goalLine: '',
          goalLineF: '',
          h: '3.950',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090769,
          updateDate: '2023-05-24',
          updateTime: '14:50:49',
        },
        {
          a: '3.320',
          d: '3.400',
          goalLine: '+1',
          goalLineF: '',
          h: '1.840',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090766,
          updateDate: '2023-05-24',
          updateTime: '14:38:29',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090766,
          updateDate: '2023-05-24',
          updateTime: '12:58:57',
        },
        {
          a: '1.730',
          d: '3.250',
          goalLine: '',
          goalLineF: '',
          h: '3.950',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090766,
          updateDate: '2023-05-24',
          updateTime: '14:50:49',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090772,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090769,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090766,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '该场比赛将在意大利-罗马举行。',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '10.00',
        s0f: '0',
        s1: '4.40',
        s1f: '0',
        s2: '3.40',
        s2f: '-1',
        s3: '3.70',
        s3f: '0',
        s4: '6.25',
        s4f: '1',
        s5: '12.00',
        s5f: '1',
        s6: '24.00',
        s6f: '1',
        s7: '36.00',
        s7f: '0',
        updateDate: '2023-05-24',
        updateTime: '12:58:57',
      },
      vote: {},
    },
    {
      awayRank: '[Group C1]',
      awayTeamAbbEnName: 'CO2',
      awayTeamAbbName: '哥伦比20',
      awayTeamAllName: '哥伦比亚U20',
      awayTeamCode: 'CO2',
      awayTeamId: 653,
      backColor: '3A5500',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '2.09',
        af: '0',
        d: '2.95',
        df: '0',
        goalLine: '',
        h: '3.12',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '13:39:20',
      },
      hafu: {},
      hhad: {
        a: '4.80',
        af: '0',
        d: '3.60',
        df: '0',
        goalLine: '+1',
        h: '1.53',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '13:39:38',
      },
      homeRank: '[Group C2]',
      homeTeamAbbEnName: 'JP2',
      homeTeamAbbName: '日本20',
      homeTeamAllName: '日本U20',
      homeTeamCode: 'JP2',
      homeTeamId: 658,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '世青赛',
      leagueAllName: '世界U20锦标赛',
      leagueCode: 'WYC',
      leagueId: 75,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019602,
      matchName: '',
      matchNum: 3006,
      matchNumStr: '周三006',
      matchStatus: 'Selling',
      matchTime: '05:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090808,
          updateDate: '2023-05-24',
          updateTime: '14:41:13',
        },
        {
          a: '2.090',
          d: '2.950',
          goalLine: '',
          goalLineF: '',
          h: '3.120',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090808,
          updateDate: '2023-05-24',
          updateTime: '13:39:20',
        },
        {
          a: '4.800',
          d: '3.600',
          goalLine: '+1',
          goalLineF: '',
          h: '1.530',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090808,
          updateDate: '2023-05-24',
          updateTime: '13:39:38',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090805,
          updateDate: '2023-05-24',
          updateTime: '14:41:13',
        },
        {
          a: '2.090',
          d: '2.950',
          goalLine: '',
          goalLineF: '',
          h: '3.120',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090805,
          updateDate: '2023-05-24',
          updateTime: '13:39:20',
        },
        {
          a: '4.800',
          d: '3.600',
          goalLine: '+1',
          goalLineF: '',
          h: '1.530',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090805,
          updateDate: '2023-05-24',
          updateTime: '13:39:38',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090806,
          updateDate: '2023-05-24',
          updateTime: '14:41:13',
        },
        {
          a: '2.090',
          d: '2.950',
          goalLine: '',
          goalLineF: '',
          h: '3.120',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090806,
          updateDate: '2023-05-24',
          updateTime: '13:39:20',
        },
        {
          a: '4.800',
          d: '3.600',
          goalLine: '+1',
          goalLineF: '',
          h: '1.530',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090806,
          updateDate: '2023-05-24',
          updateTime: '13:39:38',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090808,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090805,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090806,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '该场比赛将在阿根廷-拉普拉塔举行。',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '8.50',
        s0f: '0',
        s1: '3.85',
        s1f: '-1',
        s2: '3.25',
        s2f: '0',
        s3: '3.90',
        s3f: '0',
        s4: '6.75',
        s4f: '1',
        s5: '14.50',
        s5f: '1',
        s6: '35.00',
        s6f: '1',
        s7: '60.00',
        s7f: '1',
        updateDate: '2023-05-24',
        updateTime: '14:41:13',
      },
      vote: {},
    },
    {
      awayRank: '[Group H2]',
      awayTeamAbbEnName: 'OMP',
      awayTeamAbbName: '亚奥林',
      awayTeamAllName: '亚松森奥林匹亚',
      awayTeamCode: 'OMP',
      awayTeamId: 1614,
      backColor: '00A653',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '2.57',
        af: '0',
        d: '2.92',
        df: '0',
        goalLine: '',
        h: '2.45',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '13:16:44',
      },
      hafu: {},
      hhad: {
        a: '1.39',
        af: '0',
        d: '4.00',
        df: '0',
        goalLine: '-1',
        h: '5.90',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '13:17:01',
      },
      homeRank: '[Group H3]',
      homeTeamAbbEnName: 'PNT',
      homeTeamAbbName: '天主青年',
      homeTeamAllName: '天主教青年会',
      homeTeamCode: 'PNT',
      homeTeamId: 2302,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '解放者杯',
      leagueAllName: '南美解放者杯',
      leagueCode: 'LBC',
      leagueId: 49,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019607,
      matchName: '',
      matchNum: 3007,
      matchNumStr: '周三007',
      matchStatus: 'Selling',
      matchTime: '06:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '1.390',
          d: '4.000',
          goalLine: '-1',
          goalLineF: '',
          h: '5.900',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090736,
          updateDate: '2023-05-24',
          updateTime: '13:17:01',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090736,
          updateDate: '2023-05-24',
          updateTime: '13:36:55',
        },
        {
          a: '2.570',
          d: '2.920',
          goalLine: '',
          goalLineF: '',
          h: '2.450',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090736,
          updateDate: '2023-05-24',
          updateTime: '13:16:44',
        },
        {
          a: '1.390',
          d: '4.000',
          goalLine: '-1',
          goalLineF: '',
          h: '5.900',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090744,
          updateDate: '2023-05-24',
          updateTime: '13:17:01',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090744,
          updateDate: '2023-05-24',
          updateTime: '13:36:55',
        },
        {
          a: '2.570',
          d: '2.920',
          goalLine: '',
          goalLineF: '',
          h: '2.450',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090744,
          updateDate: '2023-05-24',
          updateTime: '13:16:44',
        },
        {
          a: '1.390',
          d: '4.000',
          goalLine: '-1',
          goalLineF: '',
          h: '5.900',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090738,
          updateDate: '2023-05-24',
          updateTime: '13:17:01',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090738,
          updateDate: '2023-05-24',
          updateTime: '13:36:55',
        },
        {
          a: '2.570',
          d: '2.920',
          goalLine: '',
          goalLineF: '',
          h: '2.450',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090738,
          updateDate: '2023-05-24',
          updateTime: '13:16:44',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090736,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090744,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090738,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '9.00',
        s0f: '0',
        s1: '4.10',
        s1f: '0',
        s2: '3.15',
        s2f: '-1',
        s3: '3.85',
        s3f: '0',
        s4: '7.00',
        s4f: '1',
        s5: '14.00',
        s5f: '1',
        s6: '29.00',
        s6f: '1',
        s7: '42.00',
        s7f: '1',
        updateDate: '2023-05-24',
        updateTime: '13:36:55',
      },
      vote: {},
    },
    {
      awayRank: '[Group C2]',
      awayTeamAbbEnName: 'PAE',
      awayTeamAbbName: '帕梅拉斯',
      awayTeamAllName: '帕尔梅拉斯',
      awayTeamCode: 'PAE',
      awayTeamId: 577,
      backColor: '00A653',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '1.71',
        af: '0',
        d: '3.40',
        df: '0',
        goalLine: '',
        h: '3.85',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '13:52:26',
      },
      hafu: {},
      hhad: {
        a: '3.17',
        af: '0',
        d: '3.50',
        df: '0',
        goalLine: '+1',
        h: '1.86',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '13:52:39',
      },
      homeRank: '[Group C4]',
      homeTeamAbbEnName: 'CEP',
      homeTeamAbbName: '波特诺',
      homeTeamAllName: '波特诺山丘',
      homeTeamCode: 'CEP',
      homeTeamId: 629,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '解放者杯',
      leagueAllName: '南美解放者杯',
      leagueCode: 'LBC',
      leagueId: 49,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019603,
      matchName: '',
      matchNum: 3008,
      matchNumStr: '周三008',
      matchStatus: 'Selling',
      matchTime: '06:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '3.170',
          d: '3.500',
          goalLine: '+1',
          goalLineF: '',
          h: '1.860',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090750,
          updateDate: '2023-05-24',
          updateTime: '13:52:39',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090750,
          updateDate: '2023-05-24',
          updateTime: '15:07:03',
        },
        {
          a: '1.710',
          d: '3.400',
          goalLine: '',
          goalLineF: '',
          h: '3.850',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090750,
          updateDate: '2023-05-24',
          updateTime: '13:52:26',
        },
        {
          a: '3.170',
          d: '3.500',
          goalLine: '+1',
          goalLineF: '',
          h: '1.860',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090741,
          updateDate: '2023-05-24',
          updateTime: '13:52:39',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090741,
          updateDate: '2023-05-24',
          updateTime: '15:07:03',
        },
        {
          a: '1.710',
          d: '3.400',
          goalLine: '',
          goalLineF: '',
          h: '3.850',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090741,
          updateDate: '2023-05-24',
          updateTime: '13:52:26',
        },
        {
          a: '3.170',
          d: '3.500',
          goalLine: '+1',
          goalLineF: '',
          h: '1.860',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090751,
          updateDate: '2023-05-24',
          updateTime: '13:52:39',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090751,
          updateDate: '2023-05-24',
          updateTime: '15:07:03',
        },
        {
          a: '1.710',
          d: '3.400',
          goalLine: '',
          goalLineF: '',
          h: '3.850',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090751,
          updateDate: '2023-05-24',
          updateTime: '13:52:26',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090750,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090741,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090751,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '13.00',
        s0f: '1',
        s1: '5.25',
        s1f: '1',
        s2: '2.90',
        s2f: '-1',
        s3: '4.10',
        s3f: '1',
        s4: '5.00',
        s4f: '-1',
        s5: '12.00',
        s5f: '0',
        s6: '24.00',
        s6f: '0',
        s7: '45.00',
        s7f: '1',
        updateDate: '2023-05-24',
        updateTime: '15:07:03',
      },
      vote: {},
    },
    {
      awayRank: '',
      awayTeamAbbEnName: 'CHF',
      awayTeamAbbName: '芝加哥',
      awayTeamAllName: '芝加哥火焰',
      awayTeamCode: 'CHF',
      awayTeamId: 902,
      backColor: '660033',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '3.35',
        af: '0',
        d: '3.35',
        df: '0',
        goalLine: '',
        h: '1.85',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:10',
      },
      hafu: {},
      hhad: {
        a: '1.70',
        af: '0',
        d: '3.60',
        df: '0',
        goalLine: '-1',
        h: '3.66',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:08',
      },
      homeRank: '',
      homeTeamAbbEnName: 'AUT',
      homeTeamAbbName: '奥斯汀FC',
      homeTeamAllName: '奥斯汀FC',
      homeTeamCode: 'AUT',
      homeTeamId: 1026677,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '公开赛杯',
      leagueAllName: '美国公开赛杯',
      leagueCode: 'MLC',
      leagueId: 87,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019608,
      matchName: '',
      matchNum: 3009,
      matchNumStr: '周三009',
      matchStatus: 'Selling',
      matchTime: '09:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090823,
          updateDate: '2023-05-24',
          updateTime: '09:54:03',
        },
        {
          a: '3.350',
          d: '3.350',
          goalLine: '',
          goalLineF: '',
          h: '1.850',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090823,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.700',
          d: '3.600',
          goalLine: '-1',
          goalLineF: '',
          h: '3.660',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090823,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090824,
          updateDate: '2023-05-24',
          updateTime: '09:54:03',
        },
        {
          a: '3.350',
          d: '3.350',
          goalLine: '',
          goalLineF: '',
          h: '1.850',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090824,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.700',
          d: '3.600',
          goalLine: '-1',
          goalLineF: '',
          h: '3.660',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090824,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090819,
          updateDate: '2023-05-24',
          updateTime: '09:54:03',
        },
        {
          a: '3.350',
          d: '3.350',
          goalLine: '',
          goalLineF: '',
          h: '1.850',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090819,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.700',
          d: '3.600',
          goalLine: '-1',
          goalLineF: '',
          h: '3.660',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090819,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090823,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090824,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090819,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '13.50',
        s0f: '0',
        s1: '5.50',
        s1f: '0',
        s2: '3.70',
        s2f: '0',
        s3: '3.60',
        s3f: '0',
        s4: '5.10',
        s4f: '0',
        s5: '9.00',
        s5f: '0',
        s6: '17.00',
        s6f: '0',
        s7: '29.00',
        s7f: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:03',
      },
      vote: {},
    },
    {
      awayRank: '',
      awayTeamAbbEnName: 'RSL',
      awayTeamAbbName: '盐湖城',
      awayTeamAllName: '皇家盐湖城',
      awayTeamCode: 'RSL',
      awayTeamId: 911,
      backColor: '660033',
      baseAwayTeamId: 0,
      baseHomeTeamId: 0,
      bettingAllUp: 0,
      bettingSingle: 0,
      businessDate: '2023-05-24',
      crs: {},
      groupName: '',
      had: {
        a: '3.30',
        af: '0',
        d: '3.45',
        df: '0',
        goalLine: '',
        h: '1.83',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:10',
      },
      hafu: {},
      hhad: {
        a: '1.70',
        af: '0',
        d: '3.62',
        df: '0',
        goalLine: '-1',
        h: '3.65',
        hf: '0',
        updateDate: '2023-05-24',
        updateTime: '09:54:08',
      },
      homeRank: '',
      homeTeamAbbEnName: 'CLR',
      homeTeamAbbName: '科罗拉多',
      homeTeamAllName: '科罗拉多急流',
      homeTeamCode: 'CLR',
      homeTeamId: 903,
      isHide: 0,
      isHot: 0,
      leagueAbbName: '公开赛杯',
      leagueAllName: '美国公开赛杯',
      leagueCode: 'MLC',
      leagueId: 87,
      lineNum: '',
      matchDate: '2023-05-25',
      matchId: 1019609,
      matchName: '',
      matchNum: 3010,
      matchNumStr: '周三010',
      matchStatus: 'Selling',
      matchTime: '10:00:00',
      matchWeek: '周三',
      oddsList: [
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090809,
          updateDate: '2023-05-24',
          updateTime: '12:29:50',
        },
        {
          a: '3.300',
          d: '3.450',
          goalLine: '',
          goalLineF: '',
          h: '1.830',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090809,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.700',
          d: '3.620',
          goalLine: '-1',
          goalLineF: '',
          h: '3.650',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090809,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090813,
          updateDate: '2023-05-24',
          updateTime: '12:29:50',
        },
        {
          a: '3.300',
          d: '3.450',
          goalLine: '',
          goalLineF: '',
          h: '1.830',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090813,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.700',
          d: '3.620',
          goalLine: '-1',
          goalLineF: '',
          h: '3.650',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090813,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
        {
          a: '',
          d: '',
          goalLine: '',
          goalLineF: '',
          h: '',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'TTG',
          poolId: 1090812,
          updateDate: '2023-05-24',
          updateTime: '12:29:50',
        },
        {
          a: '3.300',
          d: '3.450',
          goalLine: '',
          goalLineF: '',
          h: '1.830',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HAD',
          poolId: 1090812,
          updateDate: '2023-05-24',
          updateTime: '09:54:10',
        },
        {
          a: '1.700',
          d: '3.620',
          goalLine: '-1',
          goalLineF: '',
          h: '3.650',
          matchId: 0,
          matchNum: 0,
          odds: '',
          poolCode: 'HHAD',
          poolId: 1090812,
          updateDate: '2023-05-24',
          updateTime: '09:54:08',
        },
      ],
      poolList: [
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HHAD',
          poolId: 1090809,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 1,
          cbtAllUp: 1,
          cbtSingle: 1,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'TTG',
          poolId: 1090813,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 1,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
        {
          allUp: 1,
          bettingAllup: 1,
          bettingSingle: 0,
          cbtAllUp: 1,
          cbtSingle: 0,
          cbtValue: 1,
          fixedOddsgoalLine: '',
          intAllUp: 0,
          intSingle: 0,
          intValue: 2,
          matchId: 0,
          matchNum: 0,
          poolCloseDate: '',
          poolCloseTime: '',
          poolCode: 'HAD',
          poolId: 1090812,
          poolOddsType: 'F',
          poolStatus: 'Selling',
          sellInitialDate: '',
          sellInitialTime: '',
          single: 0,
          updateDate: '',
          updateTime: '',
          vbtAllUp: 0,
          vbtSingle: 0,
          vbtValue: 0,
        },
      ],
      remark: '',
      sellStatus: 1,
      ttg: {
        goalLine: '',
        s0: '13.50',
        s0f: '0',
        s1: '5.35',
        s1f: '-1',
        s2: '3.50',
        s2f: '-1',
        s3: '3.60',
        s3f: '0',
        s4: '5.30',
        s4f: '1',
        s5: '9.50',
        s5f: '1',
        s6: '18.00',
        s6f: '1',
        s7: '33.00',
        s7f: '1',
        updateDate: '2023-05-24',
        updateTime: '12:29:50',
      },
      vote: {},
    },
  ],
  weekday: '周三',
  matchCount: 10,
};
export type MatchInfo = typeof a;
