const a = {
  "businessDate": "2023-04-15",
  "subMatchList": [
      {
          "awayRank": "[瑞超6]",
          "awayTeamAbbEnName": "KAL",
          "awayTeamAbbName": "卡尔马",
          "awayTeamAllName": "卡尔马",
          "awayTeamCode": "KAL",
          "awayTeamId": 602,
          "backColor": "004488",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "5.00",
              "af": "-1",
              "d": "3.95",
              "df": "-1",
              "goalLine": "",
              "h": "1.46",
              "hf": "1",
              "updateDate": "2023-04-15",
              "updateTime": "22:47:22"
          },
          "hafu": {},
          "hhad": {
              "a": "2.23",
              "af": "-1",
              "d": "3.50",
              "df": "0",
              "goalLine": "-1",
              "h": "2.47",
              "hf": "1",
              "updateDate": "2023-04-15",
              "updateTime": "22:47:17"
          },
          "homeRank": "[瑞超1]",
          "homeTeamAbbEnName": "HAC",
          "homeTeamAbbName": "赫根",
          "homeTeamAllName": "赫根",
          "homeTeamCode": "HAC",
          "homeTeamId": 604,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "瑞超",
          "leagueAllName": "瑞典超级联赛",
          "leagueCode": "SAL",
          "leagueId": 58,
          "lineNum": "",
          "matchDate": "2023-04-15",
          "matchId": 1018986,
          "matchName": "",
          "matchNum": 6012,
          "matchNumStr": "周六012",
          "matchStatus": "Selling",
          "matchTime": "23:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "5.000",
                  "d": "3.950",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.460",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087968,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:47:22"
              },
              {
                  "a": "2.230",
                  "d": "3.500",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.470",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087968,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:47:17"
              },
              {
                  "a": "5.000",
                  "d": "3.950",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.460",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087996,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:47:22"
              },
              {
                  "a": "2.230",
                  "d": "3.500",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.470",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087996,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:47:17"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087968,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087996,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[挪超9]",
          "awayTeamAbbEnName": "LIS",
          "awayTeamAbbName": "利勒斯特",
          "awayTeamAllName": "利勒斯特罗姆",
          "awayTeamCode": "LIS",
          "awayTeamId": 619,
          "backColor": "666666",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "2.90",
              "af": "0",
              "d": "3.30",
              "df": "0",
              "goalLine": "",
              "h": "2.04",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "19:56:46"
          },
          "hafu": {},
          "hhad": {
              "a": "1.57",
              "af": "0",
              "d": "3.80",
              "df": "0",
              "goalLine": "-1",
              "h": "4.20",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "19:57:12"
          },
          "homeRank": "[挪超13]",
          "homeTeamAbbEnName": "VIK",
          "homeTeamAbbName": "维京",
          "homeTeamAllName": "维京",
          "homeTeamCode": "VIK",
          "homeTeamId": 613,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "挪超",
          "leagueAllName": "挪威超级联赛",
          "leagueCode": "NTL",
          "leagueId": 51,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018987,
          "matchName": "",
          "matchNum": 6013,
          "matchNumStr": "周六013",
          "matchStatus": "Selling",
          "matchTime": "00:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.900",
                  "d": "3.300",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "2.040",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087966,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:56:46"
              },
              {
                  "a": "1.570",
                  "d": "3.800",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "4.200",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087966,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:57:12"
              },
              {
                  "a": "2.900",
                  "d": "3.300",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "2.040",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1088045,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:56:46"
              },
              {
                  "a": "1.570",
                  "d": "3.800",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "4.200",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1088045,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:57:12"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087966,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1088045,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[俄超3]",
          "awayTeamAbbEnName": "SPM",
          "awayTeamAbbName": "莫斯巴达",
          "awayTeamAllName": "莫斯科斯巴达",
          "awayTeamCode": "SPM",
          "awayTeamId": 290,
          "backColor": "336699",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "1.22",
              "af": "-1",
              "d": "4.95",
              "df": "1",
              "goalLine": "",
              "h": "8.50",
              "hf": "1",
              "updateDate": "2023-04-15",
              "updateTime": "22:10:01"
          },
          "hafu": {},
          "hhad": {
              "a": "1.80",
              "af": "-1",
              "d": "3.55",
              "df": "0",
              "goalLine": "+1",
              "h": "3.31",
              "hf": "1",
              "updateDate": "2023-04-15",
              "updateTime": "22:10:23"
          },
          "homeRank": "[俄超16]",
          "homeTeamAbbEnName": "TOR",
          "homeTeamAbbName": "莫鱼雷",
          "homeTeamAllName": "莫斯科鱼雷",
          "homeTeamCode": "TOR",
          "homeTeamId": 339,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "俄超",
          "leagueAllName": "俄罗斯超级联赛",
          "leagueCode": "RPL",
          "leagueId": 100,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018988,
          "matchName": "",
          "matchNum": 6014,
          "matchNumStr": "周六014",
          "matchStatus": "Selling",
          "matchTime": "00:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "1.220",
                  "d": "4.950",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "8.500",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1088029,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:10:01"
              },
              {
                  "a": "1.800",
                  "d": "3.550",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "3.310",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1088029,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:10:23"
              },
              {
                  "a": "1.220",
                  "d": "4.950",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "8.500",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087985,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:10:01"
              },
              {
                  "a": "1.800",
                  "d": "3.550",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "3.310",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087985,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:10:23"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1088029,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087985,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[英超19]",
          "awayTeamAbbEnName": "LCR",
          "awayTeamAbbName": "莱切斯特",
          "awayTeamAllName": "莱切斯特城",
          "awayTeamCode": "LCR",
          "awayTeamId": 50,
          "backColor": "FF3333",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {},
          "hafu": {},
          "hhad": {
              "a": "2.67",
              "af": "1",
              "d": "4.20",
              "df": "1",
              "goalLine": "-2",
              "h": "1.90",
              "hf": "-1",
              "updateDate": "2023-04-15",
              "updateTime": "22:44:34"
          },
          "homeRank": "[英超2]",
          "homeTeamAbbEnName": "MNC",
          "homeTeamAbbName": "曼城",
          "homeTeamAllName": "曼彻斯特城",
          "homeTeamCode": "MNC",
          "homeTeamId": 12,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "英超",
          "leagueAllName": "英格兰超级联赛",
          "leagueCode": "EPL",
          "leagueId": 25,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018989,
          "matchName": "",
          "matchNum": 6015,
          "matchNumStr": "周六015",
          "matchStatus": "Selling",
          "matchTime": "00:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.670",
                  "d": "4.200",
                  "goalLine": "-2",
                  "goalLineF": "",
                  "h": "1.900",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087787,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:44:34"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 1,
                  "cbtAllUp": 1,
                  "cbtSingle": 1,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087787,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 1,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[荷甲17]",
          "awayTeamAbbEnName": "FCG",
          "awayTeamAbbName": "格罗宁根",
          "awayTeamAllName": "格罗宁根",
          "awayTeamCode": "FCG",
          "awayTeamId": 246,
          "backColor": "FF6699",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "3.88",
              "af": "1",
              "d": "3.45",
              "df": "0",
              "goalLine": "",
              "h": "1.69",
              "hf": "-1",
              "updateDate": "2023-04-15",
              "updateTime": "22:22:45"
          },
          "hafu": {},
          "hhad": {
              "a": "1.87",
              "af": "1",
              "d": "3.55",
              "df": "0",
              "goalLine": "-1",
              "h": "3.10",
              "hf": "-1",
              "updateDate": "2023-04-15",
              "updateTime": "22:23:10"
          },
          "homeRank": "[荷甲9]",
          "homeTeamAbbEnName": "RKC",
          "homeTeamAbbName": "瓦尔韦克",
          "homeTeamAllName": "瓦尔韦克",
          "homeTeamCode": "RKC",
          "homeTeamId": 252,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "荷甲",
          "leagueAllName": "荷兰甲级联赛",
          "leagueCode": "DFL",
          "leagueId": 17,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018990,
          "matchName": "",
          "matchNum": 6016,
          "matchNumStr": "周六016",
          "matchStatus": "Selling",
          "matchTime": "00:45:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "1.870",
                  "d": "3.550",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "3.100",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087901,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:23:10"
              },
              {
                  "a": "3.880",
                  "d": "3.450",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.690",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087901,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:22:45"
              },
              {
                  "a": "1.870",
                  "d": "3.550",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "3.100",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087864,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:23:10"
              },
              {
                  "a": "3.880",
                  "d": "3.450",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.690",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087864,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:22:45"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087901,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087864,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[法乙1]",
          "awayTeamAbbEnName": "LEH",
          "awayTeamAbbName": "勒阿弗尔",
          "awayTeamAllName": "勒阿弗尔",
          "awayTeamCode": "LEH",
          "awayTeamId": 194,
          "backColor": "5BC992",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "1.90",
              "af": "0",
              "d": "2.89",
              "df": "0",
              "goalLine": "",
              "h": "3.75",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:17:28"
          },
          "hafu": {},
          "hhad": {
              "a": "4.50",
              "af": "0",
              "d": "3.21",
              "df": "0",
              "goalLine": "+1",
              "h": "1.65",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "21:12:02"
          },
          "homeRank": "[法乙19]",
          "homeTeamAbbEnName": "OLN",
          "homeTeamAbbName": "尼姆",
          "homeTeamAllName": "尼姆",
          "homeTeamCode": "OLN",
          "homeTeamId": 485,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "法乙",
          "leagueAllName": "法国乙级联赛",
          "leagueCode": "FF2",
          "leagueId": 81,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018991,
          "matchName": "",
          "matchNum": 6017,
          "matchNumStr": "周六017",
          "matchStatus": "Selling",
          "matchTime": "01:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "4.500",
                  "d": "3.210",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "1.650",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087831,
                  "updateDate": "2023-04-15",
                  "updateTime": "21:12:02"
              },
              {
                  "a": "1.900",
                  "d": "2.890",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "3.750",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087831,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:17:28"
              },
              {
                  "a": "4.500",
                  "d": "3.210",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "1.650",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087803,
                  "updateDate": "2023-04-15",
                  "updateTime": "21:12:02"
              },
              {
                  "a": "1.900",
                  "d": "2.890",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "3.750",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087803,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:17:28"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087831,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087803,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[法乙13]",
          "awayTeamAbbEnName": "ANN",
          "awayTeamAbbName": "阿纳西",
          "awayTeamAllName": "阿纳西",
          "awayTeamCode": "ANN",
          "awayTeamId": 2707,
          "backColor": "5BC992",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "5.62",
              "af": "0",
              "d": "3.50",
              "df": "0",
              "goalLine": "",
              "h": "1.48",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:20:44"
          },
          "hafu": {},
          "hhad": {
              "a": "2.18",
              "af": "0",
              "d": "3.05",
              "df": "0",
              "goalLine": "-1",
              "h": "2.83",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:20:58"
          },
          "homeRank": "[法乙5]",
          "homeTeamAbbEnName": "BAT",
          "homeTeamAbbName": "巴斯蒂亚",
          "homeTeamAllName": "巴斯蒂亚",
          "homeTeamCode": "BAT",
          "homeTeamId": 175,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "法乙",
          "leagueAllName": "法国乙级联赛",
          "leagueCode": "FF2",
          "leagueId": 81,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018992,
          "matchName": "",
          "matchNum": 6018,
          "matchNumStr": "周六018",
          "matchStatus": "Selling",
          "matchTime": "01:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.180",
                  "d": "3.050",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.830",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087840,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:20:58"
              },
              {
                  "a": "5.620",
                  "d": "3.500",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.480",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087840,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:20:44"
              },
              {
                  "a": "2.180",
                  "d": "3.050",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.830",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087880,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:20:58"
              },
              {
                  "a": "5.620",
                  "d": "3.500",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.480",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087880,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:20:44"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087840,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087880,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[法乙15]",
          "awayTeamAbbEnName": "PAF",
          "awayTeamAbbName": "波城FC",
          "awayTeamAllName": "波城FC",
          "awayTeamCode": "PAF",
          "awayTeamId": 2664,
          "backColor": "5BC992",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "6.25",
              "af": "0",
              "d": "3.70",
              "df": "0",
              "goalLine": "",
              "h": "1.41",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:24:52"
          },
          "hafu": {},
          "hhad": {
              "a": "2.40",
              "af": "0",
              "d": "3.02",
              "df": "0",
              "goalLine": "-1",
              "h": "2.55",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:25:03"
          },
          "homeRank": "[法乙3]",
          "homeTeamAbbEnName": "SOC",
          "homeTeamAbbName": "索肖",
          "homeTeamAllName": "索肖",
          "homeTeamCode": "SOC",
          "homeTeamId": 189,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "法乙",
          "leagueAllName": "法国乙级联赛",
          "leagueCode": "FF2",
          "leagueId": 81,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018993,
          "matchName": "",
          "matchNum": 6019,
          "matchNumStr": "周六019",
          "matchStatus": "Selling",
          "matchTime": "01:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.400",
                  "d": "3.020",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.550",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087781,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:25:03"
              },
              {
                  "a": "6.250",
                  "d": "3.700",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.410",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087781,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:24:52"
              },
              {
                  "a": "2.400",
                  "d": "3.020",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.550",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087813,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:25:03"
              },
              {
                  "a": "6.250",
                  "d": "3.700",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.410",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087813,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:24:52"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087781,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087813,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[葡超1]",
          "awayTeamAbbEnName": "BEN",
          "awayTeamAbbName": "本菲卡",
          "awayTeamAllName": "本菲卡",
          "awayTeamCode": "BEN",
          "awayTeamId": 267,
          "backColor": "008888",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "1.15",
              "af": "0",
              "d": "5.90",
              "df": "0",
              "goalLine": "",
              "h": "10.00",
              "hf": "0",
              "updateDate": "2023-04-14",
              "updateTime": "09:40:48"
          },
          "hafu": {},
          "hhad": {
              "a": "2.62",
              "af": "0",
              "d": "3.90",
              "df": "0",
              "goalLine": "+2",
              "h": "2.00",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "17:26:03"
          },
          "homeRank": "[葡超11]",
          "homeTeamAbbEnName": "CVS",
          "homeTeamAbbName": "沙维什",
          "homeTeamAllName": "沙维什",
          "homeTeamCode": "CVS",
          "homeTeamId": 272,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "葡超",
          "leagueAllName": "葡萄牙超级联赛",
          "leagueCode": "PFL",
          "leagueId": 55,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018994,
          "matchName": "",
          "matchNum": 6020,
          "matchNumStr": "周六020",
          "matchStatus": "Selling",
          "matchTime": "01:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.620",
                  "d": "3.900",
                  "goalLine": "+2",
                  "goalLineF": "",
                  "h": "2.000",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087862,
                  "updateDate": "2023-04-15",
                  "updateTime": "17:26:03"
              },
              {
                  "a": "1.150",
                  "d": "5.900",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "10.00",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087862,
                  "updateDate": "2023-04-14",
                  "updateTime": "09:40:48"
              },
              {
                  "a": "2.620",
                  "d": "3.900",
                  "goalLine": "+2",
                  "goalLineF": "",
                  "h": "2.000",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087896,
                  "updateDate": "2023-04-15",
                  "updateTime": "17:26:03"
              },
              {
                  "a": "1.150",
                  "d": "5.900",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "10.00",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087896,
                  "updateDate": "2023-04-14",
                  "updateTime": "09:40:48"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087862,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087896,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[德乙3]",
          "awayTeamAbbEnName": "HSV",
          "awayTeamAbbName": "汉堡",
          "awayTeamAllName": "汉堡",
          "awayTeamCode": "HSV",
          "awayTeamId": 142,
          "backColor": "DB31EE",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "1.75",
              "af": "0",
              "d": "3.55",
              "df": "0",
              "goalLine": "",
              "h": "3.50",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "16:18:42"
          },
          "hafu": {},
          "hhad": {
              "a": "3.22",
              "af": "0",
              "d": "3.70",
              "df": "0",
              "goalLine": "+1",
              "h": "1.79",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "16:18:48"
          },
          "homeRank": "[德乙7]",
          "homeTeamAbbEnName": "KAI",
          "homeTeamAbbName": "凯泽",
          "homeTeamAllName": "凯泽斯劳滕",
          "homeTeamCode": "KAI",
          "homeTeamId": 145,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "德乙",
          "leagueAllName": "德国乙级联赛",
          "leagueCode": "GD2",
          "leagueId": 34,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018995,
          "matchName": "",
          "matchNum": 6021,
          "matchNumStr": "周六021",
          "matchStatus": "Selling",
          "matchTime": "02:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "3.220",
                  "d": "3.700",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "1.790",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087802,
                  "updateDate": "2023-04-15",
                  "updateTime": "16:18:48"
              },
              {
                  "a": "1.750",
                  "d": "3.550",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "3.500",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087802,
                  "updateDate": "2023-04-15",
                  "updateTime": "16:18:42"
              },
              {
                  "a": "3.220",
                  "d": "3.700",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "1.790",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087832,
                  "updateDate": "2023-04-15",
                  "updateTime": "16:18:48"
              },
              {
                  "a": "1.750",
                  "d": "3.550",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "3.500",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087832,
                  "updateDate": "2023-04-15",
                  "updateTime": "16:18:42"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087802,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087832,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[意甲13]",
          "awayTeamAbbEnName": "MOZ",
          "awayTeamAbbName": "蒙扎",
          "awayTeamAllName": "蒙扎",
          "awayTeamCode": "MOZ",
          "awayTeamId": 1039249,
          "backColor": "0066FF",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "7.30",
              "af": "0",
              "d": "4.40",
              "df": "0",
              "goalLine": "",
              "h": "1.29",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:17:55"
          },
          "hafu": {},
          "hhad": {
              "a": "2.85",
              "af": "0",
              "d": "3.45",
              "df": "0",
              "goalLine": "-1",
              "h": "2.01",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "20:18:12"
          },
          "homeRank": "[意甲5]",
          "homeTeamAbbEnName": "INM",
          "homeTeamAbbName": "国际米兰",
          "homeTeamAllName": "国际米兰",
          "homeTeamCode": "INM",
          "homeTeamId": 123,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "意甲",
          "leagueAllName": "意大利甲级联赛",
          "leagueCode": "ISA",
          "leagueId": 40,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018996,
          "matchName": "",
          "matchNum": 6022,
          "matchNumStr": "周六022",
          "matchStatus": "Selling",
          "matchTime": "02:45:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.850",
                  "d": "3.450",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.010",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087807,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:18:12"
              },
              {
                  "a": "7.300",
                  "d": "4.400",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.290",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087807,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:17:55"
              },
              {
                  "a": "2.850",
                  "d": "3.450",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.010",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087771,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:18:12"
              },
              {
                  "a": "7.300",
                  "d": "4.400",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.290",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087771,
                  "updateDate": "2023-04-15",
                  "updateTime": "20:17:55"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087807,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087771,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[西甲2]",
          "awayTeamAbbEnName": "RMD",
          "awayTeamAbbName": "皇马",
          "awayTeamAllName": "皇家马德里",
          "awayTeamCode": "RMD",
          "awayTeamId": 664,
          "backColor": "006633",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "1.42",
              "af": "0",
              "d": "4.05",
              "df": "0",
              "goalLine": "",
              "h": "5.30",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "10:23:03"
          },
          "hafu": {},
          "hhad": {
              "a": "2.36",
              "af": "0",
              "d": "3.45",
              "df": "0",
              "goalLine": "+1",
              "h": "2.35",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "10:22:59"
          },
          "homeRank": "[西甲14]",
          "homeTeamAbbEnName": "CAD",
          "homeTeamAbbName": "加的斯",
          "homeTeamAllName": "加的斯",
          "homeTeamCode": "CAD",
          "homeTeamId": 507,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "西甲",
          "leagueAllName": "西班牙甲级联赛",
          "leagueCode": "SFL",
          "leagueId": 62,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018997,
          "matchName": "",
          "matchNum": 6023,
          "matchNumStr": "周六023",
          "matchStatus": "Selling",
          "matchTime": "03:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.360",
                  "d": "3.450",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "2.350",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087887,
                  "updateDate": "2023-04-15",
                  "updateTime": "10:22:59"
              },
              {
                  "a": "1.420",
                  "d": "4.050",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "5.300",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087887,
                  "updateDate": "2023-04-15",
                  "updateTime": "10:23:03"
              },
              {
                  "a": "2.360",
                  "d": "3.450",
                  "goalLine": "+1",
                  "goalLineF": "",
                  "h": "2.350",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087849,
                  "updateDate": "2023-04-15",
                  "updateTime": "10:22:59"
              },
              {
                  "a": "1.420",
                  "d": "4.050",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "5.300",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087849,
                  "updateDate": "2023-04-15",
                  "updateTime": "10:23:03"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087887,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087849,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[法甲2]",
          "awayTeamAbbEnName": "LEN",
          "awayTeamAbbName": "朗斯",
          "awayTeamAllName": "朗斯",
          "awayTeamCode": "LEN",
          "awayTeamId": 179,
          "backColor": "6B2B2B",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "4.40",
              "af": "0",
              "d": "3.95",
              "df": "0",
              "goalLine": "",
              "h": "1.52",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "19:28:30"
          },
          "hafu": {},
          "hhad": {
              "a": "2.10",
              "af": "0",
              "d": "3.55",
              "df": "0",
              "goalLine": "-1",
              "h": "2.62",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "19:28:43"
          },
          "homeRank": "[法甲1]",
          "homeTeamAbbEnName": "PSG",
          "homeTeamAbbName": "巴黎圣曼",
          "homeTeamAllName": "巴黎圣日尔曼",
          "homeTeamCode": "PSG",
          "homeTeamId": 187,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "法甲",
          "leagueAllName": "法国甲级联赛",
          "leagueCode": "FFL",
          "leagueId": 32,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018998,
          "matchName": "",
          "matchNum": 6024,
          "matchNumStr": "周六024",
          "matchStatus": "Selling",
          "matchTime": "03:00:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.100",
                  "d": "3.550",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.620",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087823,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:28:43"
              },
              {
                  "a": "4.400",
                  "d": "3.950",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.520",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087823,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:28:30"
              },
              {
                  "a": "2.100",
                  "d": "3.550",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.620",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087795,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:28:43"
              },
              {
                  "a": "4.400",
                  "d": "3.950",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.520",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087795,
                  "updateDate": "2023-04-15",
                  "updateTime": "19:28:30"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087823,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087795,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[葡超18]",
          "awayTeamAbbEnName": "STC",
          "awayTeamAbbName": "圣克拉拉",
          "awayTeamAllName": "圣克拉拉",
          "awayTeamCode": "STC",
          "awayTeamId": 1618,
          "backColor": "008888",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {},
          "hafu": {},
          "hhad": {
              "a": "2.55",
              "af": "-1",
              "d": "3.95",
              "df": "0",
              "goalLine": "-2",
              "h": "2.03",
              "hf": "1",
              "updateDate": "2023-04-15",
              "updateTime": "22:05:15"
          },
          "homeRank": "[葡超2]",
          "homeTeamAbbEnName": "POT",
          "homeTeamAbbName": "波尔图",
          "homeTeamAllName": "波尔图",
          "homeTeamCode": "POT",
          "homeTeamId": 937,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "葡超",
          "leagueAllName": "葡萄牙超级联赛",
          "leagueCode": "PFL",
          "leagueId": 55,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1018999,
          "matchName": "",
          "matchNum": 6025,
          "matchNumStr": "周六025",
          "matchStatus": "Selling",
          "matchTime": "03:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "2.550",
                  "d": "3.950",
                  "goalLine": "-2",
                  "goalLineF": "",
                  "h": "2.030",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087869,
                  "updateDate": "2023-04-15",
                  "updateTime": "22:05:15"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087869,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[美职足8]",
          "awayTeamAbbEnName": "NSH",
          "awayTeamAbbName": "纳什维尔",
          "awayTeamAllName": "纳什维尔",
          "awayTeamCode": "NSH",
          "awayTeamId": 2706,
          "backColor": "660033",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "3.35",
              "af": "0",
              "d": "3.08",
              "df": "0",
              "goalLine": "",
              "h": "1.94",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "13:24:29"
          },
          "hafu": {},
          "hhad": {
              "a": "1.62",
              "af": "0",
              "d": "3.52",
              "df": "0",
              "goalLine": "-1",
              "h": "4.20",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "09:45:32"
          },
          "homeRank": "[美职足15]",
          "homeTeamAbbEnName": "NYY",
          "homeTeamAbbName": "纽约城",
          "homeTeamAllName": "纽约城",
          "homeTeamCode": "NYY",
          "homeTeamId": 2133,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "美职足",
          "leagueAllName": "美国职业大联盟",
          "leagueCode": "MLS",
          "leagueId": 50,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1019000,
          "matchName": "",
          "matchNum": 6026,
          "matchNumStr": "周六026",
          "matchStatus": "Selling",
          "matchTime": "07:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "3.350",
                  "d": "3.080",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.940",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087987,
                  "updateDate": "2023-04-15",
                  "updateTime": "13:24:29"
              },
              {
                  "a": "1.620",
                  "d": "3.520",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "4.200",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087987,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:32"
              },
              {
                  "a": "3.350",
                  "d": "3.080",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.940",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087956,
                  "updateDate": "2023-04-15",
                  "updateTime": "13:24:29"
              },
              {
                  "a": "1.620",
                  "d": "3.520",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "4.200",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087956,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:32"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087987,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087956,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[美职足12]",
          "awayTeamAbbEnName": "HOD",
          "awayTeamAbbName": "休斯敦",
          "awayTeamAllName": "休斯敦迪纳摩",
          "awayTeamCode": "HOD",
          "awayTeamId": 907,
          "backColor": "660033",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "5.26",
              "af": "0",
              "d": "3.65",
              "df": "0",
              "goalLine": "",
              "h": "1.48",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "09:45:19"
          },
          "hafu": {},
          "hhad": {
              "a": "2.22",
              "af": "0",
              "d": "3.20",
              "df": "0",
              "goalLine": "-1",
              "h": "2.66",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "09:45:32"
          },
          "homeRank": "[美职足20]",
          "homeTeamAbbEnName": "NYR",
          "homeTeamAbbName": "纽约红牛",
          "homeTeamAllName": "纽约红牛",
          "homeTeamCode": "NYR",
          "homeTeamId": 912,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "美职足",
          "leagueAllName": "美国职业大联盟",
          "leagueCode": "MLS",
          "leagueId": 50,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1019001,
          "matchName": "",
          "matchNum": 6027,
          "matchNumStr": "周六027",
          "matchStatus": "Selling",
          "matchTime": "07:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "5.260",
                  "d": "3.650",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.480",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087994,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:19"
              },
              {
                  "a": "2.220",
                  "d": "3.200",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.660",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087994,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:32"
              },
              {
                  "a": "5.260",
                  "d": "3.650",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.480",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1088019,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:19"
              },
              {
                  "a": "2.220",
                  "d": "3.200",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "2.660",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1088019,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:32"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087994,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1088019,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      },
      {
          "awayRank": "[美职足24]",
          "awayTeamAbbEnName": "DCU",
          "awayTeamAbbName": "华盛顿",
          "awayTeamAllName": "华盛顿联",
          "awayTeamCode": "DCU",
          "awayTeamId": 905,
          "backColor": "660033",
          "baseAwayTeamId": 0,
          "baseHomeTeamId": 0,
          "bettingAllUp": 0,
          "bettingSingle": 0,
          "businessDate": "2023-04-15",
          "crs": {},
          "groupName": "",
          "had": {
              "a": "3.06",
              "af": "0",
              "d": "3.40",
              "df": "0",
              "goalLine": "",
              "h": "1.93",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "09:45:19"
          },
          "hafu": {},
          "hhad": {
              "a": "1.65",
              "af": "0",
              "d": "3.70",
              "df": "0",
              "goalLine": "-1",
              "h": "3.80",
              "hf": "0",
              "updateDate": "2023-04-15",
              "updateTime": "09:45:32"
          },
          "homeRank": "[美职足27]",
          "homeTeamAbbEnName": "MIT",
          "homeTeamAbbName": "蒙特利尔",
          "homeTeamAllName": "蒙特利尔CF",
          "homeTeamCode": "MIT",
          "homeTeamId": 1671,
          "isHide": 0,
          "isHot": 0,
          "leagueAbbName": "美职足",
          "leagueAllName": "美国职业大联盟",
          "leagueCode": "MLS",
          "leagueId": 50,
          "lineNum": "",
          "matchDate": "2023-04-16",
          "matchId": 1019002,
          "matchName": "",
          "matchNum": 6028,
          "matchNumStr": "周六028",
          "matchStatus": "Selling",
          "matchTime": "07:30:00",
          "matchWeek": "周六",
          "oddsList": [
              {
                  "a": "3.060",
                  "d": "3.400",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.930",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087946,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:19"
              },
              {
                  "a": "1.650",
                  "d": "3.700",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "3.800",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087946,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:32"
              },
              {
                  "a": "3.060",
                  "d": "3.400",
                  "goalLine": "",
                  "goalLineF": "",
                  "h": "1.930",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HAD",
                  "poolId": 1087974,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:19"
              },
              {
                  "a": "1.650",
                  "d": "3.700",
                  "goalLine": "-1",
                  "goalLineF": "",
                  "h": "3.800",
                  "matchId": 0,
                  "matchNum": 0,
                  "odds": "",
                  "poolCode": "HHAD",
                  "poolId": 1087974,
                  "updateDate": "2023-04-15",
                  "updateTime": "09:45:32"
              }
          ],
          "poolList": [
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HAD",
                  "poolId": 1087946,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              },
              {
                  "allUp": 1,
                  "bettingAllup": 1,
                  "bettingSingle": 0,
                  "cbtAllUp": 1,
                  "cbtSingle": 0,
                  "cbtValue": 1,
                  "fixedOddsgoalLine": "",
                  "intAllUp": 0,
                  "intSingle": 0,
                  "intValue": 2,
                  "matchId": 0,
                  "matchNum": 0,
                  "poolCloseDate": "",
                  "poolCloseTime": "",
                  "poolCode": "HHAD",
                  "poolId": 1087974,
                  "poolOddsType": "F",
                  "poolStatus": "Selling",
                  "sellInitialDate": "",
                  "sellInitialTime": "",
                  "single": 0,
                  "updateDate": "",
                  "updateTime": "",
                  "vbtAllUp": 0,
                  "vbtSingle": 0,
                  "vbtValue": 0
              }
          ],
          "remark": "",
          "sellStatus": 1,
          "ttg": {},
          "vote": {}
      }
  ],
  "weekday": "周六",
  "matchCount": 17
}
export type MatchInfo = typeof a